// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: protodef/game_map.proto

package protodef

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Occupied bool `protobuf:"varint,1,opt,name=occupied,proto3" json:"occupied,omitempty"`
}

func (x *FieldStatus) Reset() {
	*x = FieldStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodef_game_map_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldStatus) ProtoMessage() {}

func (x *FieldStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protodef_game_map_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldStatus.ProtoReflect.Descriptor instead.
func (*FieldStatus) Descriptor() ([]byte, []int) {
	return file_protodef_game_map_proto_rawDescGZIP(), []int{0}
}

func (x *FieldStatus) GetOccupied() bool {
	if x != nil {
		return x.Occupied
	}
	return false
}

type XField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XFields []*FieldStatus `protobuf:"bytes,1,rep,name=x_fields,json=xFields,proto3" json:"x_fields,omitempty"`
}

func (x *XField) Reset() {
	*x = XField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodef_game_map_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XField) ProtoMessage() {}

func (x *XField) ProtoReflect() protoreflect.Message {
	mi := &file_protodef_game_map_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XField.ProtoReflect.Descriptor instead.
func (*XField) Descriptor() ([]byte, []int) {
	return file_protodef_game_map_proto_rawDescGZIP(), []int{1}
}

func (x *XField) GetXFields() []*FieldStatus {
	if x != nil {
		return x.XFields
	}
	return nil
}

type YField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YFields []*XField `protobuf:"bytes,1,rep,name=y_fields,json=yFields,proto3" json:"y_fields,omitempty"`
}

func (x *YField) Reset() {
	*x = YField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodef_game_map_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YField) ProtoMessage() {}

func (x *YField) ProtoReflect() protoreflect.Message {
	mi := &file_protodef_game_map_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YField.ProtoReflect.Descriptor instead.
func (*YField) Descriptor() ([]byte, []int) {
	return file_protodef_game_map_proto_rawDescGZIP(), []int{2}
}

func (x *YField) GetYFields() []*XField {
	if x != nil {
		return x.YFields
	}
	return nil
}

var File_protodef_game_map_proto protoreflect.FileDescriptor

var file_protodef_game_map_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x6d, 0x61, 0x70, 0x22, 0x29, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x22, 0x3a,
	0x0a, 0x06, 0x58, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x30, 0x0a, 0x08, 0x78, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x6d, 0x61, 0x70, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x07, 0x78, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x35, 0x0a, 0x06, 0x59, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x2b, 0x0a, 0x08, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6d, 0x61,
	0x70, 0x2e, 0x58, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x07, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protodef_game_map_proto_rawDescOnce sync.Once
	file_protodef_game_map_proto_rawDescData = file_protodef_game_map_proto_rawDesc
)

func file_protodef_game_map_proto_rawDescGZIP() []byte {
	file_protodef_game_map_proto_rawDescOnce.Do(func() {
		file_protodef_game_map_proto_rawDescData = protoimpl.X.CompressGZIP(file_protodef_game_map_proto_rawDescData)
	})
	return file_protodef_game_map_proto_rawDescData
}

var file_protodef_game_map_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protodef_game_map_proto_goTypes = []interface{}{
	(*FieldStatus)(nil), // 0: game_map.FieldStatus
	(*XField)(nil),      // 1: game_map.XField
	(*YField)(nil),      // 2: game_map.YField
}
var file_protodef_game_map_proto_depIdxs = []int32{
	0, // 0: game_map.XField.x_fields:type_name -> game_map.FieldStatus
	1, // 1: game_map.YField.y_fields:type_name -> game_map.XField
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protodef_game_map_proto_init() }
func file_protodef_game_map_proto_init() {
	if File_protodef_game_map_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protodef_game_map_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodef_game_map_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodef_game_map_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protodef_game_map_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protodef_game_map_proto_goTypes,
		DependencyIndexes: file_protodef_game_map_proto_depIdxs,
		MessageInfos:      file_protodef_game_map_proto_msgTypes,
	}.Build()
	File_protodef_game_map_proto = out.File
	file_protodef_game_map_proto_rawDesc = nil
	file_protodef_game_map_proto_goTypes = nil
	file_protodef_game_map_proto_depIdxs = nil
}
